Better error reporting for missing fields
Previously the current_object value would be overwritten prior to
generating the error message, causing it to display something like:

    ApiFieldError: The model 'None' has an empty attribute
    'get_absolute_url' and doesn't allow a default or null value.